import React from 'react'

export default function About() {
  return (
    <div className='container'>
        <h1 classNameName='my-3'>About the Creator</h1>
        <p>Akshat Dave is currently a UG student in Ahmedabad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde asperiores tenetur recusandae quia tempore voluptate perferendis, soluta cumque et iste qui iusto illum vero dignissimos ad aliquid veniam ducimus dolores dolorem eligendi sapiente fuga.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At, facilis ab. Doloremque ea optio architecto at assumenda asperiores a sapiente reprehenderit fuga cumque, suscipit nihil magni mollitia autem! Quo deleniti officiis debitis magni facilis culpa delectus sapiente eos id necessitatibus aspernatur maiores quia veniam laudantium, totam corporis eaque repellat, tempora nobis tenetur unde aperiam cum. Hic, distinctio pariatur expedita, iusto nesciunt cum delectus consectetur possimus, culpa amet vitae. Veritatis aspernatur temporibus debitis dolorum repudiandae consequatur corporis iste obcaecati ullam beatae officia explicabo, ut quo perferendis dignissimos velit fugiat ratione assumenda harum distinctio. Ipsam, soluta quisquam temporibus, laborum ratione mollitia dicta animi rerum iure esse quos odit! Ipsa mollitia illum, labore dignissimos pariatur voluptate nostrum corporis. Dignissimos tempora commodi nam temporibus magni voluptatem vel, porro neque nulla, asperiores optio natus dolorem? Fugit, veritatis. Soluta quam, culpa eius, laborum aliquid illo porro ex inventore voluptatum temporibus placeat rerum reprehenderit atque blanditiis a in libero quis quo voluptatibus saepe ad cupiditate quaerat? Asperiores quibusdam molestias, quos qui consequatur laborum esse minima aliquid iure facere. Obcaecati, sit similique. Accusantium, esse. Culpa sequi cumque odit hic repellendus quis totam rem, ipsum quos ad modi necessitatibus corrupti perferendis tenetur quisquam sapiente labore, impedit perspiciatis eaque? Vitae ut aliquam amet ab debitis, voluptatibus facere, doloribus nemo hic exercitationem tempore voluptatem dolor. Ducimus totam provident sint alias nam iusto, et praesentium culpa suscipit. Voluptatibus fugit numquam quo ex assumenda nihil quasi doloribus magni velit possimus cupiditate est inventore natus ad odio ab cumque nemo debitis repellendus saepe, officiis esse mollitia perspiciatis! At sint blanditiis temporibus minima rem earum, soluta delectus ratione asperiores ipsum necessitatibus neque libero quasi veniam eligendi reprehenderit exercitationem placeat suscipit optio explicabo! Quia quod, aliquam amet iste enim dicta porro nam velit magni est quae dolor ab, sequi officiis voluptates, similique adipisci! Cumque aliquid, assumenda inventore tenetur eius numquam eos accusamus magni voluptatum incidunt in iste ullam laudantium dicta, quam rerum non sed commodi autem quod. Illo placeat, harum maxime nisi facilis quod tenetur quo ipsum deleniti accusamus. Asperiores, ipsam tempora aliquam, laudantium exercitationem quibusdam impedit quos aliquid optio, minus cupiditate? At, ad!</p>
    </div>
  )
}
